### PR TITLE
Add cheri tools

### PR DESCRIPTION
**Pull request by jianyicheng**
* Added cheri dependencies with certain commits to avoid failure from upstream updates
* Added environment switching source files for docker
  * `source scripts/normal-settings.sh` enables baseline environments
  * `source scripts/cheri-settings.sh` enables CHERI

### CODE REVIEW

**Comment by mn416** [comment]
Thanks @JianyiCheng, looks promising. Will give it a try. What do you think about removing the submodules and instead doing several "git clone" in the `build-cheri.sh" script? The trouble with the submodules is that cloning the repo becomes very expensive even when you don't want to enable CHERI.

**Comment by jianyicheng** [comment]
OK. Will move them to the bash script.

**Comment by mn416** [comment]
Also wondering if we can use cheribuild's `llvm` target (rather than `sdk-riscv64-purecap`) to avoid building qemu, cheribsd, and gdb.

**Comment by jianyicheng** [comment]
> Also wondering if we can use cheribuild's `llvm` target (rather than `sdk-riscv64-purecap`) to avoid building qemu, cheribsd, and gdb.

It might be possible, but we may need to change the makefile as well - last time I tried the `make` command and it failed... 
Shall we discuss the future road map of SIMTight to see if you will need CPU/OS in future works?

**Comment by mn416** [comment]
Looks very useful. Before merging, I'd like to see:

* Changes to `inc/Config.h` dropped.
* Avoid cloning and building of `gdb`, `cheribsd`, and `qemu` (I tried the `llvm` target and it worked for me; where you using the latest `cheribuild`?).
* Rename `cheri-settings.sh` to `add-cheri-tools-to-path.sh`, and `normal-settings.sh` to `remove-cheri-tools-from-path.sh`, and move these scripts to the `cheri-tools` dir.
* Rename the build target in the root Makefile from `build` to `build-cheri-tools`; also fix the `.PHONY` attribute for this rule.

**Comment by jianyicheng** [comment]
Done. Do you know how to make `cheribuild` with LLVM only - I am not sure how to disable the others

**Comment by mn416** [comment]
> Done. Do you know how to make cheribuild with LLVM only - I am not sure how to disable the others

Is it not just `./cheribuild.py llvm`?

**Comment by jianyicheng** [comment]
Oh sorry. I did not find it in the help info... It has now been updated.

**Pull request merged**
